[package]
name = "imcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
docopt = "1.1.1"
image = "0.24.7"
term_size = "0.3.1"

